[alembic]
script_location = %(here)s/migrations
prepend_sys_path = .
sqlalchemy.url =

[alembic:runtime]
timezone = UTC

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = standard

[logger_root]
level = WARNING
handlers = console
qualname = root

[logger_sqlalchemy]
level = WARNING
handlers =
propagate = 0
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers = console
propagate = 0
qualname = alembic

[handler_console]
class = StreamHandler
level = NOTSET
args = (sys.stderr,)
formatter = standard

[formatter_standard]
format = %(asctime)s %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %%Y-%%m-%%d %%H:%%M:%%S
