"""Regenerate Adaptix-Web-App/src/lib/nemsis-registry-manifest.ts from
the backend authoritative NEMSIS registry snapshot.

Reads:
  Adaptix-EPCR-Service/backend/epcr_app/nemsis_resources/official/normalized/fields.json

Writes:
  Adaptix-Web-App/src/lib/nemsis-registry-manifest.ts

This mirrors the 654-field, 45-section, 3-dataset registry into a
deterministic TypeScript bootstrap so the frontend can surface every
NEMSIS field even when the live registry endpoint has not yet resolved.
The live backend registry endpoint remains the runtime source of truth.
"""
from __future__ import annotations

import json
from pathlib import Path


HERE = Path(__file__).resolve()
BACKEND_DIR = HERE.parents[1]  # Adaptix-EPCR-Service/backend
SERVICE_REPO = HERE.parents[2]  # Adaptix-EPCR-Service
FIELDS_JSON = (
    BACKEND_DIR
    / "epcr_app"
    / "nemsis_resources"
    / "official"
    / "normalized"
    / "fields.json"
)
WEB_APP = SERVICE_REPO.parent / "Adaptix-Web-App"
OUT = WEB_APP / "src" / "lib" / "nemsis-registry-manifest.ts"


def main() -> None:
    data = json.loads(FIELDS_JSON.read_text(encoding="utf-8"))
    by: dict[str, dict[str, list[str]]] = {}
    for f in data:
        ds = f.get("dataset") or ""
        sec = f.get("section") or ""
        fid = f.get("field_id") or f.get("element_id") or ""
        if not (ds and sec and fid):
            continue
        by.setdefault(ds, {}).setdefault(sec, []).append(fid)

    grouped = {
        ds: {sec: sorted(set(by[ds][sec])) for sec in sorted(by[ds])}
        for ds in sorted(by)
    }

    lines: list[str] = []
    a = lines.append
    a("/**")
    a(" * NEMSIS 3.5.1 registry manifest — full coverage across EMS, DEM, and State.")
    a(" *")
    a(" * Mirror of the backend authoritative registry snapshot at")
    a(" * Adaptix-EPCR-Service/backend/epcr_app/nemsis_resources/official/normalized/fields.json")
    a(" * (dictionary_version 3.5.1, baseline_total_actual=654: EMS=450, DEM=157, State=47).")
    a(" *")
    a(" * The frontend uses the live backend registry endpoint as the source of truth at")
    a(" * runtime; this manifest is the deterministic bootstrap fallback so the UI can")
    a(" * surface every NEMSIS field even when the network call has not yet resolved.")
    a(" *")
    a(" * AUTOGENERATED — do not hand-edit. To refresh, run:")
    a(" *   python Adaptix-EPCR-Service/backend/scripts/regenerate_frontend_nemsis_manifest.py")
    a(" */")
    a("")
    a('export const NEMSIS_DICTIONARY_VERSION = "3.5.1" as const;')
    a("")
    a('export type NemsisDatasetId = "EMSDataSet" | "DEMDataSet" | "StateDataSet";')
    a("")
    a("export const NEMSIS_DATASETS: readonly NemsisDatasetId[] = [")
    for ds in grouped:
        a(f'  "{ds}",')
    a("] as const;")
    a("")
    a("export const NEMSIS_DATASET_LABELS: Record<NemsisDatasetId, string> = {")
    a('  EMSDataSet: "EMS Dataset",')
    a('  DEMDataSet: "Demographic Dataset",')
    a('  StateDataSet: "State Dataset",')
    a("};")
    a("")
    a("export const NEMSIS_SECTIONS_BY_DATASET: Record<NemsisDatasetId, readonly string[]> = {")
    for ds in grouped:
        secs = ", ".join(f'"{s}"' for s in grouped[ds])
        a(f"  {ds}: [{secs}],")
    a("};")
    a("")
    a("export const NEMSIS_FIELDS_BY_DATASET: Record<NemsisDatasetId, Record<string, readonly string[]>> = {")
    for ds in grouped:
        a(f"  {ds}: {{")
        for sec in grouped[ds]:
            ids = ", ".join(f'"{i}"' for i in grouped[ds][sec])
            a(f"    {sec}: [{ids}],")
        a("  },")
    a("};")
    a("")
    a("// Flat helpers --------------------------------------------------------------")
    a("")
    a("export const ALL_NEMSIS_FIELD_IDS: readonly string[] = [")
    all_ids: list[str] = []
    for ds in grouped:
        for sec in grouped[ds]:
            all_ids.extend(grouped[ds][sec])
    for i in range(0, len(all_ids), 5):
        chunk = ", ".join(f'"{x}"' for x in all_ids[i : i + 5])
        a(f"  {chunk},")
    a("];")
    a("")
    a("export function getNemsisDatasetForSection(section: string): NemsisDatasetId | null {")
    a("  for (const ds of NEMSIS_DATASETS) {")
    a("    if ((NEMSIS_SECTIONS_BY_DATASET[ds] as readonly string[]).includes(section)) return ds;")
    a("  }")
    a("  return null;")
    a("}")
    a("")
    a("export function getNemsisFieldIdsForSection(section: string): readonly string[] {")
    a("  const ds = getNemsisDatasetForSection(section);")
    a("  if (!ds) return [];")
    a("  return NEMSIS_FIELDS_BY_DATASET[ds][section] ?? [];")
    a("}")
    a("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")

    total_fields = sum(
        len(v) for ds in grouped for v in grouped[ds].values()
    )
    total_sections = sum(len(grouped[ds]) for ds in grouped)
    print(
        f"wrote {OUT}\n"
        f"  datasets={len(grouped)} sections={total_sections} fields={total_fields}"
    )


if __name__ == "__main__":
    main()
