"""NEMSIS compliance studio scenario management and execution API routes.

Provides routes for managing and executing 2026 TAC compliance studio
scenarios. Scenarios define the test cases required for NEMSIS TAC
certification. Execution loads official NEMSIS pre-testing XML, stamps
vendor software identification fields, runs validation, persists
evidence, and submits through the live SOAP submission path.

The 2026 scenario suite uses official NEMSIS pre-testing files:
- DEM 1: Multi-state agency demographics
- EMS 1: Respiratory Transfer (interfacility)
- EMS 2: Drowning death
- EMS 3: Pediatric fire patient
- EMS 4: Canceled Standby (mutual aid)
- EMS 5: Evacuation (nursing home)

Only the elements marked 'must be auto-generated by Collect Data software'
in the official pre-testing XML are rewritten (eRecord.02/03/04 software
identification, UUID attributes, DEM timestamps). All clinical data,
NEMSIS codes, and test-case-identifying content is preserved exactly.

Routes:
- GET    /api/v1/epcr/nemsis/scenarios                              — list scenarios
- GET    /api/v1/epcr/nemsis/scenarios/{scenario_id}               — get scenario
- POST   /api/v1/epcr/nemsis/scenarios/{scenario_id}/generate      — generate XML
- POST   /api/v1/epcr/nemsis/scenarios/{scenario_id}/validate      — validate XML
- POST   /api/v1/epcr/nemsis/scenarios/{scenario_id}/submit        — submit to TAC
- GET    /api/v1/epcr/nemsis/scenarios/{scenario_id}/evidence      — get evidence
"""
from __future__ import annotations

import json
import logging
import os
import re
import uuid
from datetime import UTC, datetime, timezone
from pathlib import Path
from typing import Any

import httpx
from fastapi import APIRouter, Depends, Header, HTTPException, status
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from epcr_app.db import get_session
from epcr_app.models_nemsis_core import (
    NemsisScenario,
    NemsisSubmissionResult,
    NemsisSubmissionStatusHistory,
)
from epcr_app.nemsis_xsd_validator import NemsisXSDValidator

logger = logging.getLogger(__name__)

TAC_ENDPOINT_URL = os.environ.get(
    "NEMSIS_TAC_ENDPOINT",
    "https://cta.nemsis.org:443/ComplianceTestingWs/endpoints/",
)

NEMSIS_SCHEMA_VERSION = os.environ.get(
    "NEMSIS_SCHEMA_VERSION",
    "3.5.1",
)

PRETESTING_DIR = Path(__file__).parent / "nemsis_pretesting_v351" / "national"

SOFTWARE_CREATOR = os.environ.get("NEMSIS_SOFTWARE_CREATOR", "Adaptix Platform")
SOFTWARE_NAME = os.environ.get("NEMSIS_SOFTWARE_NAME", "Adaptix ePCR")
SOFTWARE_VERSION = os.environ.get("NEMSIS_SOFTWARE_VERSION", "1.0.0")

_PRETESTING_FILES: dict[str, str] = {
    "2026_DEM_1": "2026-DEM-1_v351.xml",
    "2026_EMS_1": "2026-EMS-1-RespiratoryTransfer_v351.xml",
    "2026_EMS_2": "2026-EMS-2-Drowning_v351.xml",
    "2026_EMS_3": "2026-EMS-3-Fire_v351.xml",
    "2026_EMS_4": "2026-EMS-4-CanceledStandby_v351.xml",
    "2026_EMS_5": "2026-EMS-5-Evacuation_v351.xml",
}

_TAC_USERNAME = os.environ.get(
    "NEMSIS_TAC_USERNAME", os.environ.get("NEMSIS_SOAP_USERNAME", "")
)
_TAC_PASSWORD = os.environ.get(
    "NEMSIS_TAC_PASSWORD", os.environ.get("NEMSIS_SOAP_PASSWORD", "")
)

_2026_SCENARIOS: list[dict[str, Any]] = [
    {
        "scenario_code": "2026_DEM_1",
        "title": "2026 DEM 1 — Multi-State Agency Demographics",
        "description": (
            "Test case for multi-state EMS agency with ground transport capability. "
            "Official NEMSIS 3.5.1 pre-testing scenario 2026-DEM-1."
        ),
        "year": 2026,
        "category": "DEM",
        "pretesting_file": "2026-DEM-1_v351.xml",
        "agency_info": {
            "state_code": "10",
            "agency_number": "351-11261",
            "agency_name": "Adaptix Platform",
        },
    },
    {
        "scenario_code": "2026_EMS_1",
        "title": "2026 EMS 1 — Respiratory Transfer",
        "description": (
            "Test case for interfacility transfer of respiratory patient. "
            "Official NEMSIS 3.5.1 pre-testing scenario 2026-EMS-1."
        ),
        "year": 2026,
        "category": "EMS",
        "pretesting_file": "2026-EMS-1-RespiratoryTransfer_v351.xml",
        "agency_info": {
            "state_code": "10",
            "agency_number": "351-11261",
            "agency_name": "Adaptix Platform",
        },
    },
    {
        "scenario_code": "2026_EMS_2",
        "title": "2026 EMS 2 — Drowning",
        "description": (
            "Test case for drowning death. "
            "Official NEMSIS 3.5.1 pre-testing scenario 2026-EMS-2."
        ),
        "year": 2026,
        "category": "EMS",
        "pretesting_file": "2026-EMS-2-Drowning_v351.xml",
        "agency_info": {
            "state_code": "10",
            "agency_number": "351-11261",
            "agency_name": "Adaptix Platform",
        },
    },
    {
        "scenario_code": "2026_EMS_3",
        "title": "2026 EMS 3 — Pediatric Fire",
        "description": (
            "Test case for pediatric fire patient. "
            "Official NEMSIS 3.5.1 pre-testing scenario 2026-EMS-3."
        ),
        "year": 2026,
        "category": "EMS",
        "pretesting_file": "2026-EMS-3-Fire_v351.xml",
        "agency_info": {
            "state_code": "10",
            "agency_number": "351-11261",
            "agency_name": "Adaptix Platform",
        },
    },
    {
        "scenario_code": "2026_EMS_4",
        "title": "2026 EMS 4 — Canceled Standby",
        "description": (
            "Test case for canceled response to a mutual aid standby request. "
            "Official NEMSIS 3.5.1 pre-testing scenario 2026-EMS-4."
        ),
        "year": 2026,
        "category": "EMS",
        "pretesting_file": "2026-EMS-4-CanceledStandby_v351.xml",
        "agency_info": {
            "state_code": "10",
            "agency_number": "351-11261",
            "agency_name": "Adaptix Platform",
        },
    },
    {
        "scenario_code": "2026_EMS_5",
        "title": "2026 EMS 5 — Evacuation",
        "description": (
            "Test case for evacuation of nursing home patient to alternative care site. "
            "Official NEMSIS 3.5.1 pre-testing scenario 2026-EMS-5."
        ),
        "year": 2026,
        "category": "EMS",
        "pretesting_file": "2026-EMS-5-Evacuation_v351.xml",
        "agency_info": {
            "state_code": "10",
            "agency_number": "351-11261",
            "agency_name": "Adaptix Platform",
        },
    },
]

router = APIRouter(prefix="/api/v1/epcr/nemsis/scenarios", tags=["nemsis-scenarios"])


class _ScenarioSummary(BaseModel):
    scenario_code: str
    title: str
    description: str
    year: int
    category: str
    status: str
    last_run_at: str | None
    last_submission_id: str | None


class _GenerateResponse(BaseModel):
    scenario_code: str
    xml_size_bytes: int
    xml_preview: str
    generated_at: str


class _ValidateResponse(BaseModel):
    scenario_code: str
    valid: bool
    validation_skipped: bool
    xsd_errors: list[str]
    schematron_errors: list[str]
    schematron_warnings: list[str]
    cardinality_errors: list[str]
    xml_size_bytes: int
    validated_at: str


class _SubmitResponse(BaseModel):
    scenario_code: str
    submission_id: str
    submission_number: str
    submission_status: str
    soap_result: dict[str, Any]
    validation_result: dict[str, Any]
    xml_size_bytes: int
    submitted_at: str


def _find_scenario(scenario_code: str) -> dict[str, Any] | None:
    for scenario in _2026_SCENARIOS:
        if scenario["scenario_code"] == scenario_code:
            return scenario
    return None


def _load_pretesting_xml(scenario_code: str) -> str | None:
    filename = _PRETESTING_FILES.get(scenario_code)
    if filename is None:
        return None
    filepath = PRETESTING_DIR / filename
    if not filepath.exists():
        logger.error("Pre-testing file not found: %s", filepath)
        return None
    return filepath.read_text(encoding="utf-8")


def _stamp_pretesting_xml(raw_xml: str, scenario_code: str) -> str:
    stamped = raw_xml

    def _fresh_uuid(match: re.Match[str]) -> str:
        return f'{match.group(1)}{uuid.uuid4()}{match.group(2)}'

    stamped = re.sub(r'(UUID=")[^"]*(")', _fresh_uuid, stamped)

    pcr_number = f"ADAPTIX-{scenario_code}-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}"
    stamped = re.sub(
        r"(<eRecord\.01>)[^<]*(</eRecord\.01>)",
        rf"\g<1>{pcr_number}\g<2>",
        stamped,
    )
    stamped = re.sub(
        r"(<eRecord\.02>)[^<]*(</eRecord\.02>)",
        rf"\g<1>{SOFTWARE_CREATOR}\g<2>",
        stamped,
    )
    stamped = re.sub(
        r"(<eRecord\.03>)[^<]*(</eRecord\.03>)",
        rf"\g<1>{SOFTWARE_NAME}\g<2>",
        stamped,
    )
    stamped = re.sub(
        r"(<eRecord\.04>)[^<]*(</eRecord\.04>)",
        rf"\g<1>{SOFTWARE_VERSION}\g<2>",
        stamped,
    )

    if "DEMDataSet" in stamped:
        now_iso = datetime.now(timezone.utc).isoformat()
        stamped = re.sub(
            r'(DemographicReport\s+timeStamp=")[^"]*(")',
            rf"\g<1>{now_iso}\g<2>",
            stamped,
        )

    return stamped


def _require_tenant(value: str | None) -> str:
    if not value or not value.strip():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="X-Tenant-ID header required",
        )
    return value.strip()


def _require_user(value: str | None) -> str:
    if not value or not value.strip():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="X-User-ID header required",
        )
    return value.strip()


def _generate_pretesting_xml_or_500(scenario_id: str, scenario: dict[str, Any]) -> bytes:
    raw_xml = _load_pretesting_xml(scenario["scenario_code"])
    if raw_xml is None:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"No official pre-testing XML available for scenario '{scenario_id}'",
        )
    xml_str = _stamp_pretesting_xml(raw_xml, scenario["scenario_code"])
    return xml_str.encode("utf-8")


def _validate_or_422(xml_bytes: bytes) -> dict[str, Any]:
    validator = NemsisXSDValidator()
    validation_result = validator.validate_xml(xml_bytes)

    if validation_result.get("validation_skipped", False):
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail={
                "error": "Validation did not run",
                "blocking_reason": validation_result.get("blocking_reason"),
                "xsd_errors": validation_result.get("xsd_errors", []),
                "schematron_errors": validation_result.get("schematron_errors", []),
                "schematron_warnings": validation_result.get("schematron_warnings", []),
                "cardinality_errors": validation_result.get("cardinality_errors", []),
            },
        )

    if not validation_result.get("valid", False):
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail={
                "error": "Validation failed",
                "xsd_errors": validation_result.get("xsd_errors", []),
                "schematron_errors": validation_result.get("schematron_errors", []),
                "schematron_warnings": validation_result.get("schematron_warnings", []),
                "cardinality_errors": validation_result.get("cardinality_errors", []),
            },
        )

    return validation_result


async def _submit_via_soap_tac(
    xml_content: bytes,
    submission_number: str,
    username: str,
    password: str,
    *,
    organization: str = "Adaptix Platform",
    data_schema: str = "61",
) -> dict[str, Any]:
    if not username or not password:
        logger.error(
            "TAC SOAP submission aborted for %s: credentials not configured",
            submission_number,
        )
        return {
            "success": False,
            "http_status": None,
            "soap_response_code": None,
            "soap_status_code": None,
            "request_handle": None,
            "error": (
                "TAC SOAP credentials not configured. "
                "Set NEMSIS_TAC_USERNAME and NEMSIS_TAC_PASSWORD environment variables."
            ),
            "endpoint_url": TAC_ENDPOINT_URL,
        }

    xml_str = xml_content.decode("utf-8", errors="strict")
    payload_xml = re.sub(r'<\?xml[^?]*\?>\s*', "", xml_str, count=1)

    soap_envelope = (
        '<?xml version="1.0" encoding="UTF-8"?>'
        '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"'
        ' xmlns:ws="http://ws.nemsis.org/">'
        "<soapenv:Header/>"
        "<soapenv:Body>"
        "<ws:SubmitDataRequest>"
        f"<ws:username>{username}</ws:username>"
        f"<ws:password>{password}</ws:password>"
        f"<ws:organization>{organization}</ws:organization>"
        "<ws:requestType>SubmitData</ws:requestType>"
        "<ws:submitPayload>"
        "<ws:payloadOfXmlElement>"
        + payload_xml
        + "</ws:payloadOfXmlElement>"
        "</ws:submitPayload>"
        f"<ws:requestDataSchema>{data_schema}</ws:requestDataSchema>"
        f"<ws:schemaVersion>{NEMSIS_SCHEMA_VERSION}</ws:schemaVersion>"
        f"<ws:additionalInfo>{submission_number}</ws:additionalInfo>"
        "</ws:SubmitDataRequest>"
        "</soapenv:Body>"
        "</soapenv:Envelope>"
    )

    headers = {
        "Content-Type": "text/xml; charset=utf-8",
        "SOAPAction": "http://ws.nemsis.org/SubmitData",
    }

    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(
                TAC_ENDPOINT_URL,
                content=soap_envelope.encode("utf-8"),
                headers=headers,
            )

        logger.info(
            "TAC SOAP submission %s: HTTP %d",
            submission_number,
            response.status_code,
        )

        if response.status_code != 200:
            return {
                "success": False,
                "http_status": response.status_code,
                "soap_response_code": str(response.status_code),
                "soap_status_code": None,
                "request_handle": None,
                "error": f"TAC endpoint returned HTTP {response.status_code}: {response.text[:500]}",
                "endpoint_url": TAC_ENDPOINT_URL,
            }

        resp_text = response.text
        status_code: int | None = None
        request_handle: str | None = None
        server_error: str | None = None

        if "<ns2:statusCode>" in resp_text:
            raw = resp_text.split("<ns2:statusCode>")[1].split("</ns2:statusCode>")[0]
            try:
                status_code = int(raw)
            except ValueError:
                status_code = None

        if "<ns2:requestHandle>" in resp_text and "</ns2:requestHandle>" in resp_text:
            rh = resp_text.split("<ns2:requestHandle>")[1].split("</ns2:requestHandle>")[0]
            if rh.strip():
                request_handle = rh.strip()

        if "<ns2:serverErrorMessage>" in resp_text and "</ns2:serverErrorMessage>" in resp_text:
            server_error = (
                resp_text.split("<ns2:serverErrorMessage>")[1]
                .split("</ns2:serverErrorMessage>")[0]
            )

        if status_code is not None and status_code > 0:
            return {
                "success": True,
                "http_status": 200,
                "soap_response_code": str(status_code),
                "soap_status_code": status_code,
                "request_handle": request_handle,
                "error": None,
                "endpoint_url": TAC_ENDPOINT_URL,
            }

        error_msg = server_error or request_handle or f"TAC returned statusCode={status_code}"
        return {
            "success": False,
            "http_status": 200,
            "soap_response_code": str(status_code) if status_code is not None else None,
            "soap_status_code": status_code,
            "request_handle": request_handle,
            "error": error_msg,
            "endpoint_url": TAC_ENDPOINT_URL,
        }

    except httpx.TimeoutException as exc:
        return {
            "success": False,
            "http_status": None,
            "soap_response_code": None,
            "soap_status_code": None,
            "request_handle": None,
            "error": f"TAC endpoint request timed out: {exc}",
            "endpoint_url": TAC_ENDPOINT_URL,
        }
    except Exception as exc:
        logger.exception(
            "TAC SOAP submission %s raised unexpected error",
            submission_number,
        )
        return {
            "success": False,
            "http_status": None,
            "soap_response_code": None,
            "soap_status_code": None,
            "request_handle": None,
            "error": f"TAC SOAP submission failed: {exc}",
            "endpoint_url": TAC_ENDPOINT_URL,
        }


@router.get(
    "/",
    response_model=list[_ScenarioSummary],
    summary="List all 2026 TAC compliance scenarios",
)
async def list_scenarios(
    x_tenant_id: str | None = Header(default=None, alias="X-Tenant-ID"),
    session: AsyncSession = Depends(get_session),
) -> list[dict[str, Any]]:
    db_states: dict[str, NemsisScenario] = {}

    if x_tenant_id:
        tenant_id = _require_tenant(x_tenant_id)
        result = await session.execute(
            select(NemsisScenario).where(
                NemsisScenario.tenant_id == tenant_id
            )
        )
        rows = result.scalars().all()
        for row in rows:
            db_states[row.scenario_code] = row

    summaries: list[dict[str, Any]] = []
    for scenario in _2026_SCENARIOS:
        code = scenario["scenario_code"]
        db_row = db_states.get(code)
        summaries.append(
            {
                "scenario_code": code,
                "title": scenario["title"],
                "description": scenario["description"],
                "year": scenario["year"],
                "category": scenario["category"],
                "status": db_row.status if db_row else "available",
                "last_run_at": db_row.last_run_at.isoformat() if db_row and db_row.last_run_at else None,
                "last_submission_id": db_row.last_submission_id if db_row else None,
            }
        )

    return summaries


@router.get(
    "/{scenario_id}",
    summary="Get a single 2026 TAC compliance scenario by code",
)
async def get_scenario(scenario_id: str) -> dict[str, Any]:
    scenario = _find_scenario(scenario_id)
    if scenario is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Scenario '{scenario_id}' not found in 2026 TAC scenario suite.",
        )
    return scenario


@router.post(
    "/{scenario_id}/generate",
    response_model=_GenerateResponse,
    summary="Generate NEMSIS XML for a TAC compliance scenario",
)
async def generate_scenario_xml(
    scenario_id: str,
    x_tenant_id: str = Header(..., alias="X-Tenant-ID"),
) -> dict[str, Any]:
    _require_tenant(x_tenant_id)

    scenario = _find_scenario(scenario_id)
    if scenario is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Scenario '{scenario_id}' not found in 2026 TAC scenario suite.",
        )

    try:
        xml_bytes = _generate_pretesting_xml_or_500(scenario_id, scenario)
    except HTTPException:
        raise
    except Exception as exc:
        logger.exception(
            "generate_scenario_xml: XML generation failed for scenario %s",
            scenario_id,
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"NEMSIS XML generation failed for scenario '{scenario_id}': {exc}",
        ) from exc

    xml_str = xml_bytes.decode("utf-8", errors="strict")
    return {
        "scenario_code": scenario["scenario_code"],
        "xml_size_bytes": len(xml_bytes),
        "xml_preview": xml_str[:2000],
        "generated_at": datetime.now(UTC).isoformat(),
    }


@router.post(
    "/{scenario_id}/validate",
    response_model=_ValidateResponse,
    summary="Generate and validate NEMSIS XML for a TAC compliance scenario",
)
async def validate_scenario_xml(
    scenario_id: str,
    x_tenant_id: str = Header(..., alias="X-Tenant-ID"),
) -> dict[str, Any]:
    _require_tenant(x_tenant_id)

    scenario = _find_scenario(scenario_id)
    if scenario is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Scenario '{scenario_id}' not found in 2026 TAC scenario suite.",
        )

    try:
        xml_bytes = _generate_pretesting_xml_or_500(scenario_id, scenario)
        validation_result = _validate_or_422(xml_bytes)
    except HTTPException:
        raise
    except Exception as exc:
        logger.exception(
            "validate_scenario_xml: validation raised unexpected error for scenario %s",
            scenario_id,
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"NEMSIS validation failed unexpectedly for scenario '{scenario_id}': {exc}",
        ) from exc

    return {
        "scenario_code": scenario["scenario_code"],
        "valid": validation_result.get("valid", False),
        "validation_skipped": validation_result.get("validation_skipped", False),
        "xsd_errors": validation_result.get("xsd_errors", []),
        "schematron_errors": validation_result.get("schematron_errors", []),
        "schematron_warnings": validation_result.get("schematron_warnings", []),
        "cardinality_errors": validation_result.get("cardinality_errors", []),
        "xml_size_bytes": len(xml_bytes),
        "validated_at": datetime.now(UTC).isoformat(),
    }


@router.post(
    "/{scenario_id}/submit",
    response_model=_SubmitResponse,
    summary="Generate, validate, and submit a TAC compliance scenario to the NEMSIS TAC endpoint",
)
async def submit_scenario(
    scenario_id: str,
    x_tenant_id: str = Header(..., alias="X-Tenant-ID"),
    x_user_id: str = Header(..., alias="X-User-ID"),
    session: AsyncSession = Depends(get_session),
) -> dict[str, Any]:
    tenant_id = _require_tenant(x_tenant_id)
    user_id = _require_user(x_user_id)

    scenario = _find_scenario(scenario_id)
    if scenario is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Scenario '{scenario_id}' not found in 2026 TAC scenario suite.",
        )

    try:
        xml_bytes = _generate_pretesting_xml_or_500(scenario_id, scenario)
        validation_result = _validate_or_422(xml_bytes)
    except HTTPException:
        raise
    except Exception as exc:
        logger.exception(
            "submit_scenario: XML generation or validation failed for scenario %s tenant %s",
            scenario_id,
            tenant_id,
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Scenario submission preparation failed for '{scenario_id}': {exc}",
        ) from exc

    submission_id = str(uuid.uuid4())
    submission_number = f"TAC-{scenario['scenario_code']}-{datetime.now(UTC).strftime('%Y%m%d%H%M%S')}"
    now_utc = datetime.now(UTC)

    soap_result = await _submit_via_soap_tac(
        xml_bytes,
        submission_number,
        _TAC_USERNAME,
        _TAC_PASSWORD,
        organization=scenario["agency_info"].get("agency_name", "Adaptix Platform"),
        data_schema="62" if scenario.get("category") == "DEM" else "61",
    )

    final_status = "submitted" if soap_result["success"] else "error"

    submission_record = NemsisSubmissionResult(
        id=submission_id,
        tenant_id=tenant_id,
        chart_id=f"SCENARIO-{scenario['scenario_code']}",
        submission_number=submission_number,
        state_endpoint_url=TAC_ENDPOINT_URL,
        submission_status=final_status,
        payload_sha256=None,
        soap_message_id=soap_result.get("request_handle"),
        soap_response_code=soap_result.get("soap_response_code"),
        rejection_reason=None if soap_result["success"] else soap_result.get("error"),
        submitted_at=now_utc if soap_result["success"] else None,
        created_at=now_utc,
        created_by_user_id=user_id,
    )
    session.add(submission_record)

    history_row = NemsisSubmissionStatusHistory(
        id=str(uuid.uuid4()),
        submission_id=submission_id,
        tenant_id=tenant_id,
        from_status=None,
        to_status=final_status,
        actor_user_id=user_id,
        note=(
            "Initial submission via TAC compliance scenario harness."
            if soap_result["success"]
            else f"Submission attempted but SOAP delivery failed: {soap_result.get('error')}"
        ),
        payload_snapshot_json=json.dumps(
            {
                "scenario_code": scenario["scenario_code"],
                "validation_valid": validation_result.get("valid"),
                "validation_skipped": validation_result.get("validation_skipped"),
                "soap_http_status": soap_result.get("http_status"),
            }
        ),
        transitioned_at=now_utc,
    )
    session.add(history_row)

    existing_scenario_result = await session.execute(
        select(NemsisScenario).where(
            NemsisScenario.scenario_code == scenario["scenario_code"],
            NemsisScenario.tenant_id == tenant_id,
        )
    )
    existing_scenario = existing_scenario_result.scalar_one_or_none()

    if existing_scenario is not None:
        existing_scenario.status = "completed" if soap_result["success"] else "failed"
        existing_scenario.last_run_at = now_utc
        existing_scenario.last_submission_id = submission_id
    else:
        new_scenario_record = NemsisScenario(
            id=str(uuid.uuid4()),
            tenant_id=tenant_id,
            scenario_code=scenario["scenario_code"],
            title=scenario["title"],
            description=scenario.get("description"),
            year=scenario["year"],
            category=scenario["category"],
            status="completed" if soap_result["success"] else "failed",
            last_run_at=now_utc,
            last_submission_id=submission_id,
            created_at=now_utc,
        )
        session.add(new_scenario_record)

    await session.commit()

    return {
        "scenario_code": scenario["scenario_code"],
        "submission_id": submission_id,
        "submission_number": submission_number,
        "submission_status": final_status,
        "soap_result": soap_result,
        "validation_result": validation_result,
        "xml_size_bytes": len(xml_bytes),
        "submitted_at": now_utc.isoformat(),
    }


@router.get(
    "/{scenario_id}/evidence",
    summary="Get execution evidence for a TAC compliance scenario",
)
async def get_scenario_evidence(
    scenario_id: str,
    x_tenant_id: str = Header(..., alias="X-Tenant-ID"),
    session: AsyncSession = Depends(get_session),
) -> dict[str, Any]:
    tenant_id = _require_tenant(x_tenant_id)

    if _find_scenario(scenario_id) is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Scenario '{scenario_id}' not found in 2026 TAC scenario suite.",
        )

    scenario_result = await session.execute(
        select(NemsisScenario).where(
            NemsisScenario.scenario_code == scenario_id,
            NemsisScenario.tenant_id == tenant_id,
        )
    )
    db_scenario = scenario_result.scalar_one_or_none()

    if db_scenario is None:
        return {
            "scenario_code": scenario_id,
            "status": "not_executed",
            "evidence": [],
        }

    evidence: dict[str, Any] = {
        "scenario_code": scenario_id,
        "status": db_scenario.status,
        "last_run_at": db_scenario.last_run_at.isoformat() if db_scenario.last_run_at else None,
        "last_submission_id": db_scenario.last_submission_id,
        "last_submission": None,
    }

    if db_scenario.last_submission_id:
        submission_result = await session.execute(
            select(NemsisSubmissionResult).where(
                NemsisSubmissionResult.id == db_scenario.last_submission_id,
                NemsisSubmissionResult.tenant_id == tenant_id,
            )
        )
        last_submission = submission_result.scalar_one_or_none()
        if last_submission is not None:
            evidence["last_submission"] = {
                "id": last_submission.id,
                "submission_number": last_submission.submission_number,
                "submission_status": last_submission.submission_status,
                "state_endpoint_url": last_submission.state_endpoint_url,
                "soap_response_code": last_submission.soap_response_code,
                "rejection_reason": last_submission.rejection_reason,
                "submitted_at": last_submission.submitted_at.isoformat() if last_submission.submitted_at else None,
                "created_at": last_submission.created_at.isoformat(),
            }

    return evidence