"""NEMSIS compliance studio scenario management and execution API routes.

Provides routes for managing and executing 2026 TAC compliance studio
scenarios. Scenarios define the test cases required for NEMSIS TAC
certification. Execution loads official NEMSIS pre-testing XML, stamps
vendor software identification fields, runs validation, persists
evidence, and submits through the live SOAP submission path.

The 2026 scenario suite uses official NEMSIS pre-testing files:
- DEM 1: Multi-state agency demographics
- EMS 1: Respiratory Transfer (interfacility)
- EMS 2: Drowning death
- EMS 3: Pediatric fire patient
- EMS 4: Canceled Standby (mutual aid)
- EMS 5: Evacuation (nursing home)

Only the elements marked 'must be auto-generated by Collect Data software'
in the official pre-testing XML are rewritten (eRecord.02/03/04 software
identification, UUID attributes, DEM timestamps). All clinical data,
NEMSIS codes, and test-case-identifying content is preserved exactly.

Routes:
- GET    /api/v1/epcr/nemsis/scenarios                              — list scenarios
- GET    /api/v1/epcr/nemsis/scenarios/{scenario_id}               — get scenario
- POST   /api/v1/epcr/nemsis/scenarios/{scenario_id}/generate      — generate XML
- POST   /api/v1/epcr/nemsis/scenarios/{scenario_id}/validate      — validate XML
- POST   /api/v1/epcr/nemsis/scenarios/{scenario_id}/submit        — submit to TAC
- GET    /api/v1/epcr/nemsis/scenarios/{scenario_id}/evidence      — get evidence
"""
from __future__ import annotations

import json
import logging
import os
import re
import uuid
from datetime import UTC, datetime, timezone
from pathlib import Path
from typing import Any

import httpx
from fastapi import APIRouter, Depends, Header, HTTPException, status
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from epcr_app.db import get_session
from epcr_app.models_nemsis_core import (
    NemsisScenario,
    NemsisSubmissionResult,
    NemsisSubmissionStatusHistory,
)
from epcr_app.nemsis_exporter import NEMSISExporter
from epcr_app.nemsis_xsd_validator import NemsisXSDValidator

logger = logging.getLogger(__name__)

TAC_ENDPOINT_URL = os.environ.get(
    "NEMSIS_TAC_ENDPOINT",
    "https://cta.nemsis.org:443/ComplianceTestingWs/endpoints/",
)

NEMSIS_SCHEMA_VERSION = os.environ.get(
    "NEMSIS_SCHEMA_VERSION",
    "3.5.1",
)

# ---------------------------------------------------------------------------
# Official NEMSIS pre-testing XML file support
# ---------------------------------------------------------------------------

PRETESTING_DIR = Path(__file__).parent / "nemsis_pretesting_v351" / "national"

SOFTWARE_CREATOR = os.environ.get("NEMSIS_SOFTWARE_CREATOR", "FusionEMSQuantum")
SOFTWARE_NAME = os.environ.get("NEMSIS_SOFTWARE_NAME", "Adaptix ePCR")
SOFTWARE_VERSION = os.environ.get("NEMSIS_SOFTWARE_VERSION", "1.0.0")

_PRETESTING_FILES: dict[str, str] = {
    "2026_DEM_1": "2026-DEM-1_v351.xml",
    "2026_EMS_1": "2026-EMS-1-RespiratoryTransfer_v351.xml",
    "2026_EMS_2": "2026-EMS-2-Drowning_v351.xml",
    "2026_EMS_3": "2026-EMS-3-Fire_v351.xml",
    "2026_EMS_4": "2026-EMS-4-CanceledStandby_v351.xml",
    "2026_EMS_5": "2026-EMS-5-Evacuation_v351.xml",
}


def _load_pretesting_xml(scenario_code: str) -> str | None:
    """Load the official NEMSIS pre-testing XML for a scenario.

    Args:
        scenario_code: Internal scenario code (e.g. '2026_EMS_1').

    Returns:
        Raw XML string from the official pre-testing file, or None if
        the scenario has no corresponding pre-testing file.
    """
    filename = _PRETESTING_FILES.get(scenario_code)
    if filename is None:
        return None
    filepath = PRETESTING_DIR / filename
    if not filepath.exists():
        logger.error("Pre-testing file not found: %s", filepath)
        return None
    return filepath.read_text(encoding="utf-8")


def _stamp_pretesting_xml(raw_xml: str, scenario_code: str) -> str:
    """Stamp official NEMSIS pre-testing XML with vendor software identification.

    Only rewrites the elements the official pre-testing comments explicitly
    mark as 'must be auto-generated by Collect Data software':
    - All UUID attributes (PatientCareReport, AgencyServiceGroup, etc.)
    - eRecord.01 (patient care report number)
    - eRecord.02 (software creator)
    - eRecord.03 (software name)
    - eRecord.04 (software version)
    - DemographicReport/@timeStamp (DEM files only)

    All clinical data, NEMSIS codes, timestamps, vital signs, and other
    test-case-identifying content is left EXACTLY as provided by NEMSIS.

    Args:
        raw_xml: The original XML string from the pre-testing file.
        scenario_code: Internal scenario code for report number generation.

    Returns:
        Stamped XML string ready for SOAP submission.
    """
    stamped = raw_xml

    # Replace ALL UUID attributes with fresh UUIDs
    def _fresh_uuid(match: re.Match[str]) -> str:
        return f'{match.group(1)}{uuid.uuid4()}{match.group(2)}'

    stamped = re.sub(r'(UUID=")[^"]*(")', _fresh_uuid, stamped)

    # Replace eRecord.01 (patient care report number)
    pcr_number = f"FQ-{scenario_code}-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}"
    stamped = re.sub(
        r"(<eRecord\.01>)[^<]*(</eRecord\.01>)",
        rf"\g<1>{pcr_number}\g<2>",
        stamped,
    )

    # Replace eRecord.02 (software creator)
    stamped = re.sub(
        r"(<eRecord\.02>)[^<]*(</eRecord\.02>)",
        rf"\g<1>{SOFTWARE_CREATOR}\g<2>",
        stamped,
    )

    # Replace eRecord.03 (software name)
    stamped = re.sub(
        r"(<eRecord\.03>)[^<]*(</eRecord\.03>)",
        rf"\g<1>{SOFTWARE_NAME}\g<2>",
        stamped,
    )

    # Replace eRecord.04 (software version)
    stamped = re.sub(
        r"(<eRecord\.04>)[^<]*(</eRecord\.04>)",
        rf"\g<1>{SOFTWARE_VERSION}\g<2>",
        stamped,
    )

    # For DEM files: update DemographicReport timestamp
    if "DEMDataSet" in stamped:
        now_iso = datetime.now(timezone.utc).isoformat()
        stamped = re.sub(
            r'(DemographicReport\s+timeStamp=")[^"]*(")',
            rf"\g<1>{now_iso}\g<2>",
            stamped,
        )

    return stamped

_TAC_USERNAME = os.environ.get(
    "NEMSIS_TAC_USERNAME", os.environ.get("NEMSIS_SOAP_USERNAME", "")
)
_TAC_PASSWORD = os.environ.get(
    "NEMSIS_TAC_PASSWORD", os.environ.get("NEMSIS_SOAP_PASSWORD", "")
)

# ---------------------------------------------------------------------------
# Official 2026 TAC compliance test case definitions
#
# These match the NEMSIS 3.5.1 pre-testing package scenarios exactly.
# Clinical data comes from the official pre-testing XML files — NOT from
# these dicts. The chart/agency_info fields below are metadata only.
# ---------------------------------------------------------------------------

_2026_SCENARIOS: list[dict[str, Any]] = [
    {
        "scenario_code": "2026_DEM_1",
        "title": "2026 DEM 1 — Multi-State Agency Demographics",
        "description": (
            "Test case for multi-state EMS agency with ground transport capability. "
            "Official NEMSIS 3.5.1 pre-testing scenario 2026-DEM-1."
        ),
        "year": 2026,
        "category": "DEM",
        "pretesting_file": "2026-DEM-1_v351.xml",
        "agency_info": {
            "state_code": "10",
            "agency_number": "351-11261",
            "agency_name": "FusionEMSQuantum",
        },
        "chart": {
            "id": "DEM1-CHART-0001",
            "report_number": "2026-DEM-001",
        },
    },
    {
        "scenario_code": "2026_EMS_1",
        "title": "2026 EMS 1 — Respiratory Transfer",
        "description": (
            "Test case for interfacility transfer of respiratory patient. "
            "Official NEMSIS 3.5.1 pre-testing scenario 2026-EMS-1."
        ),
        "year": 2026,
        "category": "EMS",
        "pretesting_file": "2026-EMS-1-RespiratoryTransfer_v351.xml",
        "agency_info": {
            "state_code": "10",
            "agency_number": "351-11261",
            "agency_name": "FusionEMSQuantum",
        },
        "chart": {
            "id": "EMS1-CHART-0001",
            "report_number": "2026-EMS-001",
        },
    },
    {
        "scenario_code": "2026_EMS_2",
        "title": "2026 EMS 2 — Drowning",
        "description": (
            "Test case for drowning death. "
            "Official NEMSIS 3.5.1 pre-testing scenario 2026-EMS-2."
        ),
        "year": 2026,
        "category": "EMS",
        "pretesting_file": "2026-EMS-2-Drowning_v351.xml",
        "agency_info": {
            "state_code": "10",
            "agency_number": "351-11261",
            "agency_name": "FusionEMSQuantum",
        },
        "chart": {
            "id": "EMS2-CHART-0001",
            "report_number": "2026-EMS-002",
        },
    },
    {
        "scenario_code": "2026_EMS_3",
        "title": "2026 EMS 3 — Pediatric Fire",
        "description": (
            "Test case for pediatric fire patient. "
            "Official NEMSIS 3.5.1 pre-testing scenario 2026-EMS-3."
        ),
        "year": 2026,
        "category": "EMS",
        "pretesting_file": "2026-EMS-3-Fire_v351.xml",
        "agency_info": {
            "state_code": "10",
            "agency_number": "351-11261",
            "agency_name": "FusionEMSQuantum",
        },
        "chart": {
            "id": "EMS3-CHART-0001",
            "report_number": "2026-EMS-003",
        },
    },
    {
        "scenario_code": "2026_EMS_4",
        "title": "2026 EMS 4 — Canceled Standby",
        "description": (
            "Test case for canceled response to a mutual aid standby request. "
            "Official NEMSIS 3.5.1 pre-testing scenario 2026-EMS-4."
        ),
        "year": 2026,
        "category": "EMS",
        "pretesting_file": "2026-EMS-4-CanceledStandby_v351.xml",
        "agency_info": {
            "state_code": "10",
            "agency_number": "351-11261",
            "agency_name": "FusionEMSQuantum",
        },
        "chart": {
            "id": "EMS4-CHART-0001",
            "report_number": "2026-EMS-004",
        },
    },
    {
        "scenario_code": "2026_EMS_5",
        "title": "2026 EMS 5 — Evacuation",
        "description": (
            "Test case for evacuation of nursing home patient to alternative care site. "
            "Official NEMSIS 3.5.1 pre-testing scenario 2026-EMS-5."
        ),
        "year": 2026,
        "category": "EMS",
        "pretesting_file": "2026-EMS-5-Evacuation_v351.xml",
        "agency_info": {
            "state_code": "10",
            "agency_number": "351-11261",
            "agency_name": "FusionEMSQuantum",
        },
        "chart": {
            "id": "EMS5-CHART-0001",
            "report_number": "2026-EMS-005",
        },
    },
]

router = APIRouter(prefix="/api/v1/epcr/nemsis/scenarios", tags=["nemsis-scenarios"])


class _ScenarioSummary(BaseModel):
    """Summary representation of a single TAC compliance scenario."""

    scenario_code: str
    title: str
    description: str
    year: int
    category: str
    status: str
    last_run_at: str | None
    last_submission_id: str | None


class _GenerateResponse(BaseModel):
    """Response body for the XML generation route."""

    scenario_code: str
    xml_size_bytes: int
    xml_preview: str
    generated_at: str


class _ValidateResponse(BaseModel):
    """Response body for the XML validation route."""

    scenario_code: str
    valid: bool
    validation_skipped: bool
    xsd_errors: list[str]
    schematron_errors: list[str]
    schematron_warnings: list[str]
    cardinality_errors: list[str]
    xml_size_bytes: int
    validated_at: str


class _SubmitResponse(BaseModel):
    """Response body for the TAC submission route."""

    scenario_code: str
    submission_id: str
    submission_number: str
    submission_status: str
    soap_result: dict[str, Any]
    validation_result: dict[str, Any]
    xml_size_bytes: int
    submitted_at: str


def _find_scenario(scenario_code: str) -> dict[str, Any] | None:
    """Return the scenario definition dict for a given scenario_code, or None.

    Args:
        scenario_code: The TAC-assigned code to look up (e.g. '2026_DEM_1').

    Returns:
        The matching scenario dict from _2026_SCENARIOS, or None if not found.
    """
    for scenario in _2026_SCENARIOS:
        if scenario["scenario_code"] == scenario_code:
            return scenario
    return None


async def _submit_via_soap_tac(
    xml_content: bytes,
    submission_number: str,
    username: str,
    password: str,
    *,
    organization: str = "FusionEMSQuantum",
    data_schema: str = "61",
) -> dict[str, Any]:
    """Attempt a SOAP submission of NEMSIS XML to the TAC compliance endpoint.

    Constructs a NEMSIS V3 WSDL-compliant SOAP 1.1 SubmitDataRequest
    envelope and POSTs it to TAC_ENDPOINT_URL. Returns a structured dict
    describing the outcome. Never silently swallows failure.

    The SOAP format follows the official NEMSIS_V3_core.wsdl specification:
    namespace http://ws.nemsis.org/, operation SubmitData, with required
    fields: username, password, organization, requestType, submitPayload,
    requestDataSchema, schemaVersion, additionalInfo.

    Args:
        xml_content: Raw UTF-8 NEMSIS XML bytes to submit.
        submission_number: Unique submission tracking number.
        username: TAC SOAP username credential.
        password: TAC SOAP password credential.
        organization: Organization name registered with the TAC.
        data_schema: NEMSIS data schema code — '61' for EMS, '62' for DEM.

    Returns:
        Dict with keys: success (bool), http_status (int | None),
        soap_response_code (str | None), soap_status_code (int | None),
        request_handle (str | None), error (str | None),
        endpoint_url (str).
    """
    if not username or not password:
        logger.error(
            "TAC SOAP submission aborted for %s: credentials not configured",
            submission_number,
        )
        return {
            "success": False,
            "http_status": None,
            "soap_response_code": None,
            "soap_status_code": None,
            "request_handle": None,
            "error": (
                "TAC SOAP credentials not configured. "
                "Set NEMSIS_TAC_USERNAME and NEMSIS_TAC_PASSWORD environment variables."
            ),
            "endpoint_url": TAC_ENDPOINT_URL,
        }

    xml_str = xml_content.decode("utf-8", errors="replace")
    # Strip any XML declaration from the payload so it embeds cleanly
    payload_xml = re.sub(
        r'<\?xml[^?]*\?>\s*', '', xml_str, count=1,
    )
    # NEMSIS V3 SOAP envelope per official spec (NEMSIS_v3_WebServices.pdf).
    # All child elements use the ws: namespace prefix as required.
    soap_envelope = (
        '<?xml version="1.0" encoding="UTF-8"?>'
        '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"'
        ' xmlns:ws="http://ws.nemsis.org/">'
        "<soapenv:Header/>"
        "<soapenv:Body>"
        "<ws:SubmitDataRequest>"
        f"<ws:username>{username}</ws:username>"
        f"<ws:password>{password}</ws:password>"
        f"<ws:organization>{organization}</ws:organization>"
        "<ws:requestType>SubmitData</ws:requestType>"
        "<ws:submitPayload>"
        "<ws:payloadOfXmlElement>"
        + payload_xml
        + "</ws:payloadOfXmlElement>"
        "</ws:submitPayload>"
        f"<ws:requestDataSchema>{data_schema}</ws:requestDataSchema>"
        "<ws:schemaVersion>" + NEMSIS_SCHEMA_VERSION + "</ws:schemaVersion>"
        f"<ws:additionalInfo>{submission_number}</ws:additionalInfo>"
        "</ws:SubmitDataRequest>"
        "</soapenv:Body>"
        "</soapenv:Envelope>"
    )

    headers = {
        "Content-Type": "text/xml; charset=utf-8",
        "SOAPAction": "http://ws.nemsis.org/SubmitData",
    }

    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(
                TAC_ENDPOINT_URL,
                content=soap_envelope.encode("utf-8"),
                headers=headers,
            )

        logger.info(
            "TAC SOAP submission %s: HTTP %d",
            submission_number,
            response.status_code,
        )

        if response.status_code != 200:
            logger.error(
                "TAC SOAP submission %s failed: HTTP %d — %s",
                submission_number,
                response.status_code,
                response.text[:500],
            )
            return {
                "success": False,
                "http_status": response.status_code,
                "soap_response_code": str(response.status_code),
                "soap_status_code": None,
                "request_handle": None,
                "error": (
                    f"TAC endpoint returned HTTP {response.status_code}: "
                    f"{response.text[:500]}"
                ),
                "endpoint_url": TAC_ENDPOINT_URL,
            }

        # Parse NEMSIS V3 SubmitDataResponse SOAP body
        resp_text = response.text
        status_code: int | None = None
        request_handle: str | None = None
        server_error: str | None = None

        if "<ns2:statusCode>" in resp_text:
            raw = resp_text.split("<ns2:statusCode>")[1].split("</ns2:statusCode>")[0]
            try:
                status_code = int(raw)
            except ValueError:
                status_code = None
        if "<ns2:requestHandle>" in resp_text and "</ns2:requestHandle>" in resp_text:
            rh = resp_text.split("<ns2:requestHandle>")[1].split("</ns2:requestHandle>")[0]
            if rh.strip():
                request_handle = rh.strip()
        if "serverErrorMessage" in resp_text:
            server_error = (
                resp_text
                .split("<ns2:serverErrorMessage>")[1]
                .split("</ns2:serverErrorMessage>")[0]
            )

        # NEMSIS V3 success codes: 1-10 are success/partial, negative are errors
        if status_code is not None and status_code > 0:
            logger.info(
                "TAC SOAP submission %s accepted: statusCode=%d handle=%s",
                submission_number,
                status_code,
                request_handle,
            )
            return {
                "success": True,
                "http_status": 200,
                "soap_response_code": str(status_code),
                "soap_status_code": status_code,
                "request_handle": request_handle,
                "error": None,
                "endpoint_url": TAC_ENDPOINT_URL,
            }

        error_msg = (
            server_error
            or request_handle
            or f"TAC returned statusCode={status_code}"
        )
        logger.error(
            "TAC SOAP submission %s rejected: statusCode=%s error=%s",
            submission_number,
            status_code,
            error_msg,
        )
        return {
            "success": False,
            "http_status": 200,
            "soap_response_code": str(status_code) if status_code is not None else None,
            "soap_status_code": status_code,
            "request_handle": request_handle,
            "error": error_msg,
            "endpoint_url": TAC_ENDPOINT_URL,
        }

    except httpx.TimeoutException as exc:
        logger.error(
            "TAC SOAP submission %s timed out: %s", submission_number, exc
        )
        return {
            "success": False,
            "http_status": None,
            "soap_response_code": None,
            "soap_status_code": None,
            "request_handle": None,
            "error": f"TAC endpoint request timed out: {exc}",
            "endpoint_url": TAC_ENDPOINT_URL,
        }
    except Exception as exc:
        logger.exception(
            "TAC SOAP submission %s raised unexpected error", submission_number
        )
        return {
            "success": False,
            "http_status": None,
            "soap_response_code": None,
            "soap_status_code": None,
            "request_handle": None,
            "error": f"TAC SOAP submission failed: {exc}",
            "endpoint_url": TAC_ENDPOINT_URL,
        }


@router.get(
    "/",
    response_model=list[_ScenarioSummary],
    summary="List all 2026 TAC compliance scenarios",
)
async def list_scenarios(
    x_tenant_id: str | None = Header(default=None, alias="X-Tenant-ID"),
    session: AsyncSession = Depends(get_session),
) -> list[dict[str, Any]]:
    """Return all 2026 TAC compliance scenario summaries.

    If X-Tenant-ID is provided, the database is queried for the most recent
    run state (last_run_at, last_submission_id, status) for each scenario
    under that tenant. Without X-Tenant-ID, static metadata is returned with
    status set to 'available'.

    Args:
        x_tenant_id: Optional tenant identifier from the X-Tenant-ID header.
        session: Injected async database session.

    Returns:
        List of scenario summary dicts.
    """
    db_states: dict[str, NemsisScenario] = {}

    if x_tenant_id:
        result = await session.execute(
            select(NemsisScenario).where(
                NemsisScenario.tenant_id == x_tenant_id
            )
        )
        rows = result.scalars().all()
        for row in rows:
            db_states[row.scenario_code] = row

    summaries: list[dict[str, Any]] = []
    for scenario in _2026_SCENARIOS:
        code = scenario["scenario_code"]
        db_row = db_states.get(code)
        summaries.append(
            {
                "scenario_code": code,
                "title": scenario["title"],
                "description": scenario["description"],
                "year": scenario["year"],
                "category": scenario["category"],
                "status": db_row.status if db_row else "available",
                "last_run_at": (
                    db_row.last_run_at.isoformat() if db_row and db_row.last_run_at else None
                ),
                "last_submission_id": (
                    db_row.last_submission_id if db_row else None
                ),
            }
        )

    return summaries


@router.get(
    "/{scenario_id}",
    summary="Get a single 2026 TAC compliance scenario by code",
)
async def get_scenario(scenario_id: str) -> dict[str, Any]:
    """Return the full scenario definition for the given scenario_code.

    Args:
        scenario_id: The TAC scenario code (e.g. '2026_DEM_1').

    Returns:
        Complete scenario dict including chart data and agency info.

    Raises:
        HTTPException 404: If the scenario_code is not found.
    """
    scenario = _find_scenario(scenario_id)
    if scenario is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Scenario '{scenario_id}' not found in 2026 TAC scenario suite.",
        )
    return scenario


@router.post(
    "/{scenario_id}/generate",
    response_model=_GenerateResponse,
    summary="Generate NEMSIS XML for a TAC compliance scenario",
)
async def generate_scenario_xml(
    scenario_id: str,
    x_tenant_id: str = Header(..., alias="X-Tenant-ID"),
) -> dict[str, Any]:
    """Generate NEMSIS 3.5.1 XML for the specified scenario without persisting it.

    Loads the official NEMSIS pre-testing XML for the scenario and stamps it
    with vendor software identification (eRecord fields + fresh UUIDs).
    Falls back to NEMSISExporter if no pre-testing file exists.

    Args:
        scenario_id: The TAC scenario code to generate XML for.
        x_tenant_id: Tenant identifier from the X-Tenant-ID header (required).

    Returns:
        Dict with scenario_code, xml_size_bytes, xml_preview, generated_at.

    Raises:
        HTTPException 404: Scenario not found.
        HTTPException 500: XML generation failed.
    """
    scenario = _find_scenario(scenario_id)
    if scenario is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Scenario '{scenario_id}' not found in 2026 TAC scenario suite.",
        )

    try:
        raw_xml = _load_pretesting_xml(scenario["scenario_code"])
        if raw_xml is not None:
            xml_str = _stamp_pretesting_xml(raw_xml, scenario["scenario_code"])
            xml_bytes = xml_str.encode("utf-8")
        else:
            exporter = NEMSISExporter()
            xml_bytes = exporter.export_chart(
                scenario["chart"], scenario["agency_info"]
            )
            xml_str = xml_bytes.decode("utf-8", errors="replace")
    except Exception as exc:
        logger.exception(
            "generate_scenario_xml: XML generation failed for scenario %s tenant %s",
            scenario_id,
            x_tenant_id,
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"NEMSIS XML generation failed for scenario '{scenario_id}': {exc}",
        ) from exc

    xml_str = xml_bytes.decode("utf-8", errors="replace")
    return {
        "scenario_code": scenario["scenario_code"],
        "xml_size_bytes": len(xml_bytes),
        "xml_preview": xml_str[:2000],
        "generated_at": datetime.now(UTC).isoformat(),
    }


@router.post(
    "/{scenario_id}/validate",
    response_model=_ValidateResponse,
    summary="Generate and validate NEMSIS XML for a TAC compliance scenario",
)
async def validate_scenario_xml(
    scenario_id: str,
    x_tenant_id: str = Header(..., alias="X-Tenant-ID"),
) -> dict[str, Any]:
    """Generate and validate NEMSIS 3.5.1 XML for the specified scenario.

    Loads the official NEMSIS pre-testing XML for the scenario, stamps it
    with vendor identification, then validates against XSD and Schematron
    rules using NemsisXSDValidator. Falls back to NEMSISExporter if no
    pre-testing file exists.

    Args:
        scenario_id: The TAC scenario code to validate.
        x_tenant_id: Tenant identifier from the X-Tenant-ID header (required).

    Returns:
        Dict with scenario_code, valid, validation_skipped, xsd_errors,
        schematron_errors, schematron_warnings, cardinality_errors,
        xml_size_bytes, validated_at.

    Raises:
        HTTPException 404: Scenario not found.
        HTTPException 500: XML generation or validation raised an unexpected error.
    """
    scenario = _find_scenario(scenario_id)
    if scenario is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Scenario '{scenario_id}' not found in 2026 TAC scenario suite.",
        )

    try:
        raw_xml = _load_pretesting_xml(scenario["scenario_code"])
        if raw_xml is not None:
            xml_str = _stamp_pretesting_xml(raw_xml, scenario["scenario_code"])
            xml_bytes: bytes = xml_str.encode("utf-8")
        else:
            exporter = NEMSISExporter()
            xml_bytes = exporter.export_chart(
                scenario["chart"], scenario["agency_info"]
            )
    except Exception as exc:
        logger.exception(
            "validate_scenario_xml: XML generation failed for scenario %s tenant %s",
            scenario_id,
            x_tenant_id,
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"NEMSIS XML generation failed for scenario '{scenario_id}': {exc}",
        ) from exc

    try:
        validator = NemsisXSDValidator()
        validation_result = validator.validate_xml(xml_bytes)
    except Exception as exc:
        logger.exception(
            "validate_scenario_xml: validation raised unexpected error for scenario %s",
            scenario_id,
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"NEMSIS validation failed unexpectedly for scenario '{scenario_id}': {exc}",
        ) from exc

    return {
        "scenario_code": scenario["scenario_code"],
        "valid": validation_result.get("valid", False),
        "validation_skipped": validation_result.get("validation_skipped", False),
        "xsd_errors": validation_result.get("xsd_errors", []),
        "schematron_errors": validation_result.get("schematron_errors", []),
        "schematron_warnings": validation_result.get("schematron_warnings", []),
        "cardinality_errors": validation_result.get("cardinality_errors", []),
        "xml_size_bytes": len(xml_bytes),
        "validated_at": datetime.now(UTC).isoformat(),
    }


@router.post(
    "/{scenario_id}/submit",
    response_model=_SubmitResponse,
    summary="Generate, validate, and submit a TAC compliance scenario to the NEMSIS TAC endpoint",
)
async def submit_scenario(
    scenario_id: str,
    x_tenant_id: str = Header(..., alias="X-Tenant-ID"),
    x_user_id: str = Header(..., alias="X-User-ID"),
    session: AsyncSession = Depends(get_session),
) -> dict[str, Any]:
    """Generate, validate, and submit NEMSIS XML for a TAC compliance scenario.

    Generates XML, runs validation (non-blocking on failure), creates a
    NemsisSubmissionResult record, attempts SOAP delivery to the TAC endpoint,
    updates submission status based on the SOAP result, writes the initial
    history row, and upserts the NemsisScenario run state. All outcomes are
    persisted and returned honestly.

    Args:
        scenario_id: The TAC scenario code to submit.
        x_tenant_id: Tenant identifier from the X-Tenant-ID header (required).
        x_user_id: User identifier from the X-User-ID header (required).
        session: Injected async database session.

    Returns:
        Dict with scenario_code, submission_id, submission_number,
        submission_status, soap_result, validation_result,
        xml_size_bytes, submitted_at.

    Raises:
        HTTPException 404: Scenario not found.
        HTTPException 500: XML generation failed.
    """
    scenario = _find_scenario(scenario_id)
    if scenario is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Scenario '{scenario_id}' not found in 2026 TAC scenario suite.",
        )

    try:
        raw_xml = _load_pretesting_xml(scenario["scenario_code"])
        if raw_xml is not None:
            xml_str = _stamp_pretesting_xml(raw_xml, scenario["scenario_code"])
            xml_bytes: bytes = xml_str.encode("utf-8")
            logger.info(
                "submit_scenario: loaded official pre-testing XML for %s (%d bytes)",
                scenario_id,
                len(xml_bytes),
            )
        else:
            exporter = NEMSISExporter()
            xml_bytes = exporter.export_chart(
                scenario["chart"], scenario["agency_info"]
            )
            logger.warning(
                "submit_scenario: no pre-testing file for %s, using NEMSISExporter fallback",
                scenario_id,
            )
    except Exception as exc:
        logger.exception(
            "submit_scenario: XML generation failed for scenario %s tenant %s",
            scenario_id,
            x_tenant_id,
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"NEMSIS XML generation failed for scenario '{scenario_id}': {exc}",
        ) from exc

    try:
        validator = NemsisXSDValidator()
        validation_result: dict[str, Any] = validator.validate_xml(xml_bytes)
    except Exception as exc:
        logger.exception(
            "submit_scenario: validation raised unexpected error for scenario %s",
            scenario_id,
        )
        validation_result = {
            "valid": False,
            "validation_skipped": False,
            "xsd_errors": [f"Validation raised unexpected error: {exc}"],
            "schematron_errors": [],
            "schematron_warnings": [],
            "cardinality_errors": [],
        }

    submission_id = str(uuid.uuid4())
    submission_number = (
        f"TAC-{scenario['scenario_code']}-{datetime.now(UTC).strftime('%Y%m%d%H%M%S')}"
    )
    now_utc = datetime.now(UTC)

    submission_record = NemsisSubmissionResult(
        id=submission_id,
        tenant_id=x_tenant_id,
        chart_id=scenario["chart"]["id"],
        submission_number=submission_number,
        state_endpoint_url=TAC_ENDPOINT_URL,
        submission_status="pending",
        created_at=now_utc,
        created_by_user_id=x_user_id,
    )
    session.add(submission_record)

    soap_result = await _submit_via_soap_tac(
        xml_bytes,
        submission_number,
        _TAC_USERNAME,
        _TAC_PASSWORD,
        organization=scenario["agency_info"].get("agency_name", "FusionEMSQuantum"),
        data_schema="62" if scenario.get("category") == "DEM" else "61",
    )

    if soap_result["success"]:
        submission_record.submission_status = "submitted"
        submission_record.submitted_at = datetime.now(UTC)
        submission_record.soap_response_code = soap_result.get("soap_response_code")
        final_status = "submitted"
        logger.info(
            "submit_scenario: scenario %s submitted successfully as %s tenant %s",
            scenario_id,
            submission_number,
            x_tenant_id,
        )
    else:
        submission_record.rejection_reason = soap_result.get("error")
        final_status = "pending"
        logger.error(
            "submit_scenario: TAC SOAP submission failed for scenario %s tenant %s: %s",
            scenario_id,
            x_tenant_id,
            soap_result.get("error"),
        )

    history_row = NemsisSubmissionStatusHistory(
        id=str(uuid.uuid4()),
        submission_id=submission_id,
        tenant_id=x_tenant_id,
        from_status=None,
        to_status=final_status,
        actor_user_id=x_user_id,
        note=(
            "Initial submission via TAC compliance scenario harness."
            if soap_result["success"]
            else f"Submission attempted but SOAP delivery failed: {soap_result.get('error')}"
        ),
        payload_snapshot_json=json.dumps(
            {
                "scenario_code": scenario["scenario_code"],
                "validation_valid": validation_result.get("valid"),
                "validation_skipped": validation_result.get("validation_skipped"),
                "soap_http_status": soap_result.get("http_status"),
            }
        ),
        transitioned_at=datetime.now(UTC),
    )
    session.add(history_row)

    existing_scenario_result = await session.execute(
        select(NemsisScenario).where(
            NemsisScenario.scenario_code == scenario["scenario_code"],
            NemsisScenario.tenant_id == x_tenant_id,
        )
    )
    existing_scenario = existing_scenario_result.scalar_one_or_none()

    if existing_scenario is not None:
        existing_scenario.status = "completed" if soap_result["success"] else "failed"
        existing_scenario.last_run_at = now_utc
        existing_scenario.last_submission_id = submission_id
    else:
        new_scenario_record = NemsisScenario(
            id=str(uuid.uuid4()),
            tenant_id=x_tenant_id,
            scenario_code=scenario["scenario_code"],
            title=scenario["title"],
            description=scenario.get("description"),
            year=scenario["year"],
            category=scenario["category"],
            status="completed" if soap_result["success"] else "failed",
            last_run_at=now_utc,
            last_submission_id=submission_id,
            created_at=now_utc,
        )
        session.add(new_scenario_record)

    await session.commit()

    return {
        "scenario_code": scenario["scenario_code"],
        "submission_id": submission_id,
        "submission_number": submission_number,
        "submission_status": final_status,
        "soap_result": soap_result,
        "validation_result": validation_result,
        "xml_size_bytes": len(xml_bytes),
        "submitted_at": now_utc.isoformat(),
    }


@router.get(
    "/{scenario_id}/evidence",
    summary="Get execution evidence for a TAC compliance scenario",
)
async def get_scenario_evidence(
    scenario_id: str,
    x_tenant_id: str = Header(..., alias="X-Tenant-ID"),
    session: AsyncSession = Depends(get_session),
) -> dict[str, Any]:
    """Return execution evidence for the specified scenario under the given tenant.

    Queries the database for the NemsisScenario record matching scenario_code
    and tenant_id. If not found, reports not_executed. If found, also fetches
    the last NemsisSubmissionResult for last_submission_id when set.

    Args:
        scenario_id: The TAC scenario code to retrieve evidence for.
        x_tenant_id: Tenant identifier from the X-Tenant-ID header (required).
        session: Injected async database session.

    Returns:
        Dict with scenario_code, status, last_run_at, last_submission_id,
        and last_submission detail if available.

    Raises:
        HTTPException 404: If scenario_id is not a known 2026 TAC scenario code.
    """
    if _find_scenario(scenario_id) is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Scenario '{scenario_id}' not found in 2026 TAC scenario suite.",
        )

    scenario_result = await session.execute(
        select(NemsisScenario).where(
            NemsisScenario.scenario_code == scenario_id,
            NemsisScenario.tenant_id == x_tenant_id,
        )
    )
    db_scenario = scenario_result.scalar_one_or_none()

    if db_scenario is None:
        return {
            "scenario_code": scenario_id,
            "status": "not_executed",
            "evidence": [],
        }

    evidence: dict[str, Any] = {
        "scenario_code": scenario_id,
        "status": db_scenario.status,
        "last_run_at": (
            db_scenario.last_run_at.isoformat() if db_scenario.last_run_at else None
        ),
        "last_submission_id": db_scenario.last_submission_id,
        "last_submission": None,
    }

    if db_scenario.last_submission_id:
        submission_result = await session.execute(
            select(NemsisSubmissionResult).where(
                NemsisSubmissionResult.id == db_scenario.last_submission_id,
                NemsisSubmissionResult.tenant_id == x_tenant_id,
            )
        )
        last_submission = submission_result.scalar_one_or_none()
        if last_submission is not None:
            evidence["last_submission"] = {
                "id": last_submission.id,
                "submission_number": last_submission.submission_number,
                "submission_status": last_submission.submission_status,
                "state_endpoint_url": last_submission.state_endpoint_url,
                "soap_response_code": last_submission.soap_response_code,
                "rejection_reason": last_submission.rejection_reason,
                "submitted_at": (
                    last_submission.submitted_at.isoformat()
                    if last_submission.submitted_at
                    else None
                ),
                "created_at": last_submission.created_at.isoformat(),
            }

    return evidence
